### ISSUE TITLE
Implement redesign profile screen

### ISSUE THREAD

**Issue by janitaroyseth** [janitaroyseth/solveit#65]

**Comment by FaizFk** [comment]
Hi I want to make the profile screen.
Do you have any figma design or should I do this on my own. I can share some dribble design if you want to discuss.

**Comment by pr0xity** [comment]
> Hi I want to make the profile screen. Do you have any figma design or should I do this on my own. I can share some dribble design if you want to discuss.

Hello @FaizFk.
Thank you for your interest in the project.

If you look under [contributing](https://github.com/janital/solveIt#contributing) in the readme, you'll see that this project is not open for outside contributions as this is a school project.

**Comment by FaizFk** [comment]
Oh...Ok sorry I did'nt saw that.
Nevermind🙂
